apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstoneproject5
  template:
    metadata:
      labels:
        app: capstoneproject5
    spec:
      containers:
      - name: capstone-project5
        image: himangirewatkar/capstoneproject5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject5
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: capstoneproject5
